apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secret
  namespace: default
type: Opaque
stringData:
  s3-access-key: {{ .Values.backup.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.backup.s3SecretKey | quote }}
