# kube-prometheus-stack values
# Prometheus + Grafana + Alertmanager + node-exporter + kube-state-metrics
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    additionalScrapeConfigs:
      - job_name: node-exporter-internal
        static_configs:
          - targets:
              - 10.0.1.10:9100
              - 10.0.1.11:9100
        relabel_configs:
          - source_labels: [__address__]
            regex: '10\.0\.1\.10:.*'
            target_label: node
            replacement: sre-node-1
          - source_labels: [__address__]
            regex: '10\.0\.1\.11:.*'
            target_label: node
            replacement: sre-node-2

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

nodeExporter:
  enabled: true

prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: false

kubeStateMetrics:
  enabled: true
