---
- name: Pre-answer debconf for iptables-persistent
  shell: |
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections
  become: true

- name: Download fail2ban-telegram script
  get_url:
    url: https://raw.githubusercontent.com/Oni-Wan-Shinobi/fail2ban-telegram/main/fail2ban-telegram.sh
    dest: /tmp/fail2ban-telegram.sh
    mode: '0755'

- name: Run fail2ban-telegram installer
  shell: |
    printf '1\n{{ telegram_token }}\n{{ telegram_chat_id }}\n{{ whitelist_ip }}\n{{ whitelist_ip_extra }}\n5\nn\nn\n22\n' | bash /tmp/fail2ban-telegram.sh
  args:
    creates: /etc/fail2ban/action.d/two-stage-ban.conf
