---
- name: Download server-activity script
  get_url:
    url: https://raw.githubusercontent.com/Oni-Wan-Shinobi/server-activity-telegram.sh/main/server-activity-telegram.sh
    dest: /tmp/server-activity-telegram.sh
    mode: '0755'

- name: Run server-activity installer
  shell: |
    printf '1\n{{ telegram_token_activity }}\n{{ telegram_chat_id }}\n3600\n' | bash /tmp/server-activity-telegram.sh
  args:
    creates: /usr/local/bin/tg_login.sh
